version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: deflow-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=deflow

  redis:
    image: redis:7
    container_name: deflow-redis
    ports:
      - '6379:6379'

volumes:
  mongo_data:
